/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class directCameraReadout_andorsdk3v2_AndorSDK3v2 */

#ifndef _Included_directCameraReadout_andorsdk3v2_AndorSDK3v2
#define _Included_directCameraReadout_andorsdk3v2_AndorSDK3v2
#ifdef __cplusplus
extern "C" {
#endif
#undef directCameraReadout_andorsdk3v2_AndorSDK3v2_impwinposx
#define directCameraReadout_andorsdk3v2_AndorSDK3v2_impwinposx 1110L
#undef directCameraReadout_andorsdk3v2_AndorSDK3v2_impwinposy
#define directCameraReadout_andorsdk3v2_AndorSDK3v2_impwinposy 125L
/*
 * Class:     directCameraReadout_andorsdk3v2_AndorSDK3v2
 * Method:    seyHello
 * Signature: (II)F
 */
JNIEXPORT jfloat JNICALL Java_directCameraReadout_andorsdk3v2_AndorSDK3v2_seyHello
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     directCameraReadout_andorsdk3v2_AndorSDK3v2
 * Method:    sayHello
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_directCameraReadout_andorsdk3v2_AndorSDK3v2_sayHello
  (JNIEnv *, jobject);

/*
 * Class:     directCameraReadout_andorsdk3v2_AndorSDK3v2
 * Method:    isSCMOSconnectedSDK3
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_directCameraReadout_andorsdk3v2_AndorSDK3v2_isSCMOSconnectedSDK3
  (JNIEnv *, jclass);

/*
 * Class:     directCameraReadout_andorsdk3v2_AndorSDK3v2
 * Method:    ShutDownSDK3
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_directCameraReadout_andorsdk3v2_AndorSDK3v2_ShutDownSDK3
  (JNIEnv *, jclass);

/*
 * Class:     directCameraReadout_andorsdk3v2_AndorSDK3v2
 * Method:    SystemShutDownSDK3
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_directCameraReadout_andorsdk3v2_AndorSDK3v2_SystemShutDownSDK3
  (JNIEnv *, jclass);

/*
 * Class:     directCameraReadout_andorsdk3v2_AndorSDK3v2
 * Method:    InitializeSystemSDK3
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_directCameraReadout_andorsdk3v2_AndorSDK3v2_InitializeSystemSDK3
  (JNIEnv *, jclass);

/*
 * Class:     directCameraReadout_andorsdk3v2_AndorSDK3v2
 * Method:    GetEnumeratedStringSDK3
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_directCameraReadout_andorsdk3v2_AndorSDK3v2_GetEnumeratedStringSDK3
  (JNIEnv *, jclass, jstring);

/*
 * Class:     directCameraReadout_andorsdk3v2_AndorSDK3v2
 * Method:    GetIntegerValueSDK3
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_directCameraReadout_andorsdk3v2_AndorSDK3v2_GetIntegerValueSDK3
  (JNIEnv *, jclass, jstring);

/*
 * Class:     directCameraReadout_andorsdk3v2_AndorSDK3v2
 * Method:    GetDoubleValueSDK3
 * Signature: (Ljava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_directCameraReadout_andorsdk3v2_AndorSDK3v2_GetDoubleValueSDK3
  (JNIEnv *, jclass, jstring);

/*
 * Class:     directCameraReadout_andorsdk3v2_AndorSDK3v2
 * Method:    GetStringValueSDK3
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_directCameraReadout_andorsdk3v2_AndorSDK3v2_GetStringValueSDK3
  (JNIEnv *, jclass, jstring);

/*
 * Class:     directCameraReadout_andorsdk3v2_AndorSDK3v2
 * Method:    GetBooleanValueSDK3
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_directCameraReadout_andorsdk3v2_AndorSDK3v2_GetBooleanValueSDK3
  (JNIEnv *, jclass, jstring);

/*
 * Class:     directCameraReadout_andorsdk3v2_AndorSDK3v2
 * Method:    GetEnumCountSDK3
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_directCameraReadout_andorsdk3v2_AndorSDK3v2_GetEnumCountSDK3
  (JNIEnv *, jclass, jstring);

/*
 * Class:     directCameraReadout_andorsdk3v2_AndorSDK3v2
 * Method:    GetEnumStringByIndexSDK3
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_directCameraReadout_andorsdk3v2_AndorSDK3v2_GetEnumStringByIndexSDK3
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     directCameraReadout_andorsdk3v2_AndorSDK3v2
 * Method:    GetFloatMaxSDK3
 * Signature: (Ljava/lang/String;)F
 */
JNIEXPORT jfloat JNICALL Java_directCameraReadout_andorsdk3v2_AndorSDK3v2_GetFloatMaxSDK3
  (JNIEnv *, jclass, jstring);

/*
 * Class:     directCameraReadout_andorsdk3v2_AndorSDK3v2
 * Method:    GetFloatMinSDK3
 * Signature: (Ljava/lang/String;)F
 */
JNIEXPORT jfloat JNICALL Java_directCameraReadout_andorsdk3v2_AndorSDK3v2_GetFloatMinSDK3
  (JNIEnv *, jclass, jstring);

/*
 * Class:     directCameraReadout_andorsdk3v2_AndorSDK3v2
 * Method:    GetIntMaxSDK3
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_directCameraReadout_andorsdk3v2_AndorSDK3v2_GetIntMaxSDK3
  (JNIEnv *, jclass, jstring);

/*
 * Class:     directCameraReadout_andorsdk3v2_AndorSDK3v2
 * Method:    GetIntMinSDK3
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_directCameraReadout_andorsdk3v2_AndorSDK3v2_GetIntMinSDK3
  (JNIEnv *, jclass, jstring);

/*
 * Class:     directCameraReadout_andorsdk3v2_AndorSDK3v2
 * Method:    SetEnumeratedStringSDK3
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_directCameraReadout_andorsdk3v2_AndorSDK3v2_SetEnumeratedStringSDK3
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     directCameraReadout_andorsdk3v2_AndorSDK3v2
 * Method:    SetIntegerValueSDK3
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_directCameraReadout_andorsdk3v2_AndorSDK3v2_SetIntegerValueSDK3
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     directCameraReadout_andorsdk3v2_AndorSDK3v2
 * Method:    SetDoubleValueSDK3
 * Signature: (Ljava/lang/String;D)I
 */
JNIEXPORT jint JNICALL Java_directCameraReadout_andorsdk3v2_AndorSDK3v2_SetDoubleValueSDK3
  (JNIEnv *, jclass, jstring, jdouble);

/*
 * Class:     directCameraReadout_andorsdk3v2_AndorSDK3v2
 * Method:    SetBooleanValueSDK3
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_directCameraReadout_andorsdk3v2_AndorSDK3v2_SetBooleanValueSDK3
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     directCameraReadout_andorsdk3v2_AndorSDK3v2
 * Method:    SetEnumIndexSDK3
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_directCameraReadout_andorsdk3v2_AndorSDK3v2_SetEnumIndexSDK3
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     directCameraReadout_andorsdk3v2_AndorSDK3v2
 * Method:    setParameterSingleSDK3
 * Signature: (DIIIIII)V
 */
JNIEXPORT void JNICALL Java_directCameraReadout_andorsdk3v2_AndorSDK3v2_setParameterSingleSDK3
  (JNIEnv *, jclass, jdouble, jint, jint, jint, jint, jint, jint);

/*
 * Class:     directCameraReadout_andorsdk3v2_AndorSDK3v2
 * Method:    runSingleScanSDK3
 * Signature: ()[S
 */
JNIEXPORT jshortArray JNICALL Java_directCameraReadout_andorsdk3v2_AndorSDK3v2_runSingleScanSDK3
  (JNIEnv *, jclass);

/*
 * Class:     directCameraReadout_andorsdk3v2_AndorSDK3v2
 * Method:    setParameterInfiniteLoopSDK3
 * Signature: (IIIDIIIIIIIII)V
 */
JNIEXPORT void JNICALL Java_directCameraReadout_andorsdk3v2_AndorSDK3v2_setParameterInfiniteLoopSDK3
  (JNIEnv *, jclass, jint, jint, jint, jdouble, jint, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     directCameraReadout_andorsdk3v2_AndorSDK3v2
 * Method:    runInfiniteLoopSDK3
 * Signature: ([SLdirectCameraReadout/control/FrameCounter;)V
 */
JNIEXPORT void JNICALL Java_directCameraReadout_andorsdk3v2_AndorSDK3v2_runInfiniteLoopSDK3
  (JNIEnv *, jclass, jshortArray, jobject);

/*
 * Class:     directCameraReadout_andorsdk3v2_AndorSDK3v2
 * Method:    setStopMechanismSDK3
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_directCameraReadout_andorsdk3v2_AndorSDK3v2_setStopMechanismSDK3
  (JNIEnv *, jclass, jboolean);

#ifdef __cplusplus
}
#endif
#endif
