/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class directCameraReadout_andorsdk2v3_AndorSDK2v3 */

#ifndef _Included_directCameraReadout_andorsdk2v3_AndorSDK2v3
#define _Included_directCameraReadout_andorsdk2v3_AndorSDK2v3
#ifdef __cplusplus
extern "C" {
#endif
#undef directCameraReadout_andorsdk2v3_AndorSDK2v3_impwinposx
#define directCameraReadout_andorsdk2v3_AndorSDK2v3_impwinposx 1110L
#undef directCameraReadout_andorsdk2v3_AndorSDK2v3_impwinposy
#define directCameraReadout_andorsdk2v3_AndorSDK2v3_impwinposy 125L
/*
 * Class:     directCameraReadout_andorsdk2v3_AndorSDK2v3
 * Method:    seyHello
 * Signature: (II)F
 */
JNIEXPORT jfloat JNICALL Java_directCameraReadout_andorsdk2v3_AndorSDK2v3_seyHello
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     directCameraReadout_andorsdk2v3_AndorSDK2v3
 * Method:    sayHello
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_directCameraReadout_andorsdk2v3_AndorSDK2v3_sayHello
  (JNIEnv *, jobject);

/*
 * Class:     directCameraReadout_andorsdk2v3_AndorSDK2v3
 * Method:    InitializeEMCCDSDK2
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_directCameraReadout_andorsdk2v3_AndorSDK2v3_InitializeEMCCDSDK2
  (JNIEnv *, jclass);

/*
 * Class:     directCameraReadout_andorsdk2v3_AndorSDK2v3
 * Method:    SystemShutDownSDK2
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_directCameraReadout_andorsdk2v3_AndorSDK2v3_SystemShutDownSDK2
  (JNIEnv *, jclass);

/*
 * Class:     directCameraReadout_andorsdk2v3_AndorSDK2v3
 * Method:    ShutDownSDK2
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_directCameraReadout_andorsdk2v3_AndorSDK2v3_ShutDownSDK2
  (JNIEnv *, jclass);

/*
 * Class:     directCameraReadout_andorsdk2v3_AndorSDK2v3
 * Method:    getMinMaxTemperatureSDK2
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_directCameraReadout_andorsdk2v3_AndorSDK2v3_getMinMaxTemperatureSDK2
  (JNIEnv *, jclass);

/*
 * Class:     directCameraReadout_andorsdk2v3_AndorSDK2v3
 * Method:    SetTemperatureSDK2
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_directCameraReadout_andorsdk2v3_AndorSDK2v3_SetTemperatureSDK2
  (JNIEnv *, jclass, jint);

/*
 * Class:     directCameraReadout_andorsdk2v3_AndorSDK2v3
 * Method:    SetCoolingSDK2
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_directCameraReadout_andorsdk2v3_AndorSDK2v3_SetCoolingSDK2
  (JNIEnv *, jclass, jint);

/*
 * Class:     directCameraReadout_andorsdk2v3_AndorSDK2v3
 * Method:    GetTemperatureAndStatusSDK2
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_directCameraReadout_andorsdk2v3_AndorSDK2v3_GetTemperatureAndStatusSDK2
  (JNIEnv *, jclass);

/*
 * Class:     directCameraReadout_andorsdk2v3_AndorSDK2v3
 * Method:    SetFanModeSDK2
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_directCameraReadout_andorsdk2v3_AndorSDK2v3_SetFanModeSDK2
  (JNIEnv *, jclass, jint);

/*
 * Class:     directCameraReadout_andorsdk2v3_AndorSDK2v3
 * Method:    DoCameraAcquisitionSDK2
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_directCameraReadout_andorsdk2v3_AndorSDK2v3_DoCameraAcquisitionSDK2
  (JNIEnv *, jclass);

/*
 * Class:     directCameraReadout_andorsdk2v3_AndorSDK2v3
 * Method:    setStopMechanismSDK2
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_directCameraReadout_andorsdk2v3_AndorSDK2v3_setStopMechanismSDK2
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     directCameraReadout_andorsdk2v3_AndorSDK2v3
 * Method:    isEMCCDconnectedSDK2
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_directCameraReadout_andorsdk2v3_AndorSDK2v3_isEMCCDconnectedSDK2
  (JNIEnv *, jclass);

/*
 * Class:     directCameraReadout_andorsdk2v3_AndorSDK2v3
 * Method:    setParameterSingleSDK2
 * Signature: (FIIIIIIIIIIIIIIIII)V
 */
JNIEXPORT void JNICALL Java_directCameraReadout_andorsdk2v3_AndorSDK2v3_setParameterSingleSDK2
  (JNIEnv *, jclass, jfloat, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     directCameraReadout_andorsdk2v3_AndorSDK2v3
 * Method:    runSingleScanSDK2
 * Signature: ()[S
 */
JNIEXPORT jshortArray JNICALL Java_directCameraReadout_andorsdk2v3_AndorSDK2v3_runSingleScanSDK2
  (JNIEnv *, jclass);

/*
 * Class:     directCameraReadout_andorsdk2v3_AndorSDK2v3
 * Method:    setParameterInfiniteLoopSDK2
 * Signature: (IIFIIIIIIIIIIIIIIIIII)Z
 */
JNIEXPORT jboolean JNICALL Java_directCameraReadout_andorsdk2v3_AndorSDK2v3_setParameterInfiniteLoopSDK2
  (JNIEnv *, jclass, jint, jint, jfloat, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     directCameraReadout_andorsdk2v3_AndorSDK2v3
 * Method:    runInfiniteLoopSDK2
 * Signature: ([SLdirectCameraReadout/control/FrameCounter;)V
 */
JNIEXPORT void JNICALL Java_directCameraReadout_andorsdk2v3_AndorSDK2v3_runInfiniteLoopSDK2
  (JNIEnv *, jclass, jshortArray, jobject);

/*
 * Class:     directCameraReadout_andorsdk2v3_AndorSDK2v3
 * Method:    setParameterContinuousAcquisitionSDK2
 * Signature: (IIIFIIIIIIIIIIIIIIIIII)Z
 */
JNIEXPORT jboolean JNICALL Java_directCameraReadout_andorsdk2v3_AndorSDK2v3_setParameterContinuousAcquisitionSDK2
  (JNIEnv *, jclass, jint, jint, jint, jfloat, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     directCameraReadout_andorsdk2v3_AndorSDK2v3
 * Method:    runContinuousScanAcquisitionSDK2
 * Signature: ([SLdirectCameraReadout/control/FrameCounter;)V
 */
JNIEXPORT void JNICALL Java_directCameraReadout_andorsdk2v3_AndorSDK2v3_runContinuousScanAcquisitionSDK2
  (JNIEnv *, jclass, jshortArray, jobject);

/*
 * Class:     directCameraReadout_andorsdk2v3_AndorSDK2v3
 * Method:    setParameterInfiniteLoopV2SDK2
 * Signature: (IIFIIIIIIIIIIIIIIIII)Z
 */
JNIEXPORT jboolean JNICALL Java_directCameraReadout_andorsdk2v3_AndorSDK2v3_setParameterInfiniteLoopV2SDK2
  (JNIEnv *, jclass, jint, jint, jfloat, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     directCameraReadout_andorsdk2v3_AndorSDK2v3
 * Method:    runInfiniteLoopV2SDK2
 * Signature: ([S)V
 */
JNIEXPORT void JNICALL Java_directCameraReadout_andorsdk2v3_AndorSDK2v3_runInfiniteLoopV2SDK2
  (JNIEnv *, jclass, jshortArray);

/*
 * Class:     directCameraReadout_andorsdk2v3_AndorSDK2v3
 * Method:    getDetectorDimensionSDK2
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_directCameraReadout_andorsdk2v3_AndorSDK2v3_getDetectorDimensionSDK2
  (JNIEnv *, jclass);

/*
 * Class:     directCameraReadout_andorsdk2v3_AndorSDK2v3
 * Method:    getEMGainSDK2
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_directCameraReadout_andorsdk2v3_AndorSDK2v3_getEMGainSDK2
  (JNIEnv *, jclass);

/*
 * Class:     directCameraReadout_andorsdk2v3_AndorSDK2v3
 * Method:    getFrameTransferSDK2
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_directCameraReadout_andorsdk2v3_AndorSDK2v3_getFrameTransferSDK2
  (JNIEnv *, jclass);

/*
 * Class:     directCameraReadout_andorsdk2v3_AndorSDK2v3
 * Method:    getPreAmpGainSDK2
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_directCameraReadout_andorsdk2v3_AndorSDK2v3_getPreAmpGainSDK2
  (JNIEnv *, jclass);

/*
 * Class:     directCameraReadout_andorsdk2v3_AndorSDK2v3
 * Method:    getVSSpeedSDK2
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_directCameraReadout_andorsdk2v3_AndorSDK2v3_getVSSpeedSDK2
  (JNIEnv *, jclass);

/*
 * Class:     directCameraReadout_andorsdk2v3_AndorSDK2v3
 * Method:    getVSClockVoltageSDK2
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_directCameraReadout_andorsdk2v3_AndorSDK2v3_getVSClockVoltageSDK2
  (JNIEnv *, jclass);

/*
 * Class:     directCameraReadout_andorsdk2v3_AndorSDK2v3
 * Method:    getnADchannelsSDK2
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_directCameraReadout_andorsdk2v3_AndorSDK2v3_getnADchannelsSDK2
  (JNIEnv *, jclass);

/*
 * Class:     directCameraReadout_andorsdk2v3_AndorSDK2v3
 * Method:    getHSSpeedSDK2
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_directCameraReadout_andorsdk2v3_AndorSDK2v3_getHSSpeedSDK2
  (JNIEnv *, jclass);

/*
 * Class:     directCameraReadout_andorsdk2v3_AndorSDK2v3
 * Method:    getNoAvailableHSSpeedSDK2
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_directCameraReadout_andorsdk2v3_AndorSDK2v3_getNoAvailableHSSpeedSDK2
  (JNIEnv *, jclass);

/*
 * Class:     directCameraReadout_andorsdk2v3_AndorSDK2v3
 * Method:    getFastestVerticalSpeedSDK2
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_directCameraReadout_andorsdk2v3_AndorSDK2v3_getFastestVerticalSpeedSDK2
  (JNIEnv *, jclass);

/*
 * Class:     directCameraReadout_andorsdk2v3_AndorSDK2v3
 * Method:    getKineticCycleSDK2
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_directCameraReadout_andorsdk2v3_AndorSDK2v3_getKineticCycleSDK2
  (JNIEnv *, jclass);

/*
 * Class:     directCameraReadout_andorsdk2v3_AndorSDK2v3
 * Method:    getExposureTimeSDK2
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_directCameraReadout_andorsdk2v3_AndorSDK2v3_getExposureTimeSDK2
  (JNIEnv *, jclass);

/*
 * Class:     directCameraReadout_andorsdk2v3_AndorSDK2v3
 * Method:    getBaseLineClampStateSDK2
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_directCameraReadout_andorsdk2v3_AndorSDK2v3_getBaseLineClampStateSDK2
  (JNIEnv *, jclass);

/*
 * Class:     directCameraReadout_andorsdk2v3_AndorSDK2v3
 * Method:    getBaseLineOffsetSDK2
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_directCameraReadout_andorsdk2v3_AndorSDK2v3_getBaseLineOffsetSDK2
  (JNIEnv *, jclass);

/*
 * Class:     directCameraReadout_andorsdk2v3_AndorSDK2v3
 * Method:    getBitDepthSDK2
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_directCameraReadout_andorsdk2v3_AndorSDK2v3_getBitDepthSDK2
  (JNIEnv *, jclass);

/*
 * Class:     directCameraReadout_andorsdk2v3_AndorSDK2v3
 * Method:    getisCoolerOnSDK2
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_directCameraReadout_andorsdk2v3_AndorSDK2v3_getisCoolerOnSDK2
  (JNIEnv *, jclass);

/*
 * Class:     directCameraReadout_andorsdk2v3_AndorSDK2v3
 * Method:    getWidthSDK2
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_directCameraReadout_andorsdk2v3_AndorSDK2v3_getWidthSDK2
  (JNIEnv *, jclass);

/*
 * Class:     directCameraReadout_andorsdk2v3_AndorSDK2v3
 * Method:    getHeightSDK2
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_directCameraReadout_andorsdk2v3_AndorSDK2v3_getHeightSDK2
  (JNIEnv *, jclass);

/*
 * Class:     directCameraReadout_andorsdk2v3_AndorSDK2v3
 * Method:    getLeftSDK2
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_directCameraReadout_andorsdk2v3_AndorSDK2v3_getLeftSDK2
  (JNIEnv *, jclass);

/*
 * Class:     directCameraReadout_andorsdk2v3_AndorSDK2v3
 * Method:    getTopSDK2
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_directCameraReadout_andorsdk2v3_AndorSDK2v3_getTopSDK2
  (JNIEnv *, jclass);

/*
 * Class:     directCameraReadout_andorsdk2v3_AndorSDK2v3
 * Method:    getCameraSerialNumSDK2
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_directCameraReadout_andorsdk2v3_AndorSDK2v3_getCameraSerialNumSDK2
  (JNIEnv *, jclass);

/*
 * Class:     directCameraReadout_andorsdk2v3_AndorSDK2v3
 * Method:    getHeadModelSDK2
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_directCameraReadout_andorsdk2v3_AndorSDK2v3_getHeadModelSDK2
  (JNIEnv *, jclass);

/*
 * Class:     directCameraReadout_andorsdk2v3_AndorSDK2v3
 * Method:    GetArrayZero
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_directCameraReadout_andorsdk2v3_AndorSDK2v3_GetArrayZero
  (JNIEnv *, jclass);

/*
 * Class:     directCameraReadout_andorsdk2v3_AndorSDK2v3
 * Method:    GetArrayndZero
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_directCameraReadout_andorsdk2v3_AndorSDK2v3_GetArrayndZero
  (JNIEnv *, jclass);

/*
 * Class:     directCameraReadout_andorsdk2v3_AndorSDK2v3
 * Method:    GetArraydiscardZero
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_directCameraReadout_andorsdk2v3_AndorSDK2v3_GetArraydiscardZero
  (JNIEnv *, jclass);

/*
 * Class:     directCameraReadout_andorsdk2v3_AndorSDK2v3
 * Method:    GetStringArray
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_directCameraReadout_andorsdk2v3_AndorSDK2v3_GetStringArray
  (JNIEnv *, jclass);

/*
 * Class:     directCameraReadout_andorsdk2v3_AndorSDK2v3
 * Method:    GetAvailableVSAmplitudeSDK2
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_directCameraReadout_andorsdk2v3_AndorSDK2v3_GetAvailableVSAmplitudeSDK2
  (JNIEnv *, jclass);

/*
 * Class:     directCameraReadout_andorsdk2v3_AndorSDK2v3
 * Method:    GetAvailableVSSpeedsSDK2
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_directCameraReadout_andorsdk2v3_AndorSDK2v3_GetAvailableVSSpeedsSDK2
  (JNIEnv *, jclass);

/*
 * Class:     directCameraReadout_andorsdk2v3_AndorSDK2v3
 * Method:    GetAvailableHSSpeedsSDK2
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_directCameraReadout_andorsdk2v3_AndorSDK2v3_GetAvailableHSSpeedsSDK2
  (JNIEnv *, jclass);

/*
 * Class:     directCameraReadout_andorsdk2v3_AndorSDK2v3
 * Method:    GetAvailablePreAmpGainSDK2
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_directCameraReadout_andorsdk2v3_AndorSDK2v3_GetAvailablePreAmpGainSDK2
  (JNIEnv *, jclass);

/*
 * Class:     directCameraReadout_andorsdk2v3_AndorSDK2v3
 * Method:    ShutterControlSDK2
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_directCameraReadout_andorsdk2v3_AndorSDK2v3_ShutterControlSDK2
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     directCameraReadout_andorsdk2v3_AndorSDK2v3
 * Method:    TESTsetParam
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_directCameraReadout_andorsdk2v3_AndorSDK2v3_TESTsetParam
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     directCameraReadout_andorsdk2v3_AndorSDK2v3
 * Method:    TESTcropMode
 * Signature: (IIIIIII)V
 */
JNIEXPORT void JNICALL Java_directCameraReadout_andorsdk2v3_AndorSDK2v3_TESTcropMode
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
